## ������������
server:
    port: 8080

## spring�������
spring:
    ## ����Դ����
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/opendev?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        # ʹ��druid����Դ
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    ## redis����
    redis:
        host: 127.0.0.1
        port: 6379
        password : 123456
        timeout: 1800
        jedis:
            pool:
                max-active: 8
                max-idle: 8
                min-idle: 0


## �����ýڵ�Ϊ�����Ľڵ㣬�кܶ�ͬѧ���׽�������÷���spring�Ľڵ��£����������޷���ʶ��
mybatis:
    mapper-locations: com.opendev.mapper.xml.*.xml  #ע�⣺һ��Ҫ��Ӧmapperӳ��xml�ļ�������·��
    type-aliases-package: com.opendev.model  # ע�⣺��Ӧʵ�����·��

#pagehelper��ҳ���
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

##��־����
logging:
    level:
      com.opendev: DEBUG

